### ISSUE TITLE
Build FAILED!

### ISSUE THREAD

**Issue by pahaz** [aio-libs/sockjs#20]
Hi! I submit new pull requiest. After ci tests pass I see many errors:

```
Traceback (most recent call last):
  File "/home/travis/build/aio-libs/sockjs/tests/test_route.py", line 213, in test_fail_transport
    'transport': 'test', 'session': 'session', 'server': '000'})
  File "/home/travis/build/aio-libs/sockjs/tests/test_route.py", line 52, in make_request
    False, False)
TypeError: __new__() missing 1 required positional argument: 'compression'
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
--------------------- >> end captured logging << ---------------------
```

This is not a my pull request problem. 

Plese rebuild CI build.

**Comment by pahaz** [comment]
Please rebuild ci

**Comment by pahaz** [comment]
Fixed: https://github.com/aio-libs/sockjs/pull/19

**Comment by pahaz** [comment]
@asvetlov, hi! Could you please provide recomendations for backward aiohttp incompatibility changes?

The problem in this commit: https://github.com/KeepSafe/aiohttp/commit/fa06acc2392c516491bdb25301ad3ef2b700ff5f 

*Are these changes come in the next release?* 

This PR https://github.com/aio-libs/sockjs/pull/19 work with current aiohttp master, but it does not work with the current stable version (0.20.2).

https://travis-ci.org/aio-libs/sockjs/jobs/106509469#L341 - master tests (ok)
https://travis-ci.org/aio-libs/sockjs/jobs/106509469#L1150 - 0.20.2 tests (error)

**Comment by pahaz** [comment]
fixed in https://github.com/aio-libs/sockjs/issues/19
